
-- Create a table for cabang (branches)
CREATE TABLE public.cabang (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.cabang ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "select_cabang" ON public.cabang
  FOR SELECT USING (true);

CREATE POLICY "insert_cabang" ON public.cabang
  FOR INSERT WITH CHECK (true);

CREATE POLICY "update_cabang" ON public.cabang
  FOR UPDATE USING (true);

CREATE POLICY "delete_cabang" ON public.cabang
  FOR DELETE USING (true);
