
-- Create a table for pembelian (purchases)
CREATE TABLE public.pembelian (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_pembelian date NOT NULL,
  divisi character varying NOT NULL CHECK (divisi IN ('sport', 'start')),
  cabang_id integer NOT NULL REFERENCES cabang(id),
  jenis_pembelian character varying NOT NULL CHECK (jenis_pembelian IN ('Tukar Tambah', 'Bukan Tukar Tambah')),
  brand_id integer NOT NULL REFERENCES brands(id),
  jenis_motor_id integer NOT NULL REFERENCES jenis_motor(id),
  tahun integer NOT NULL CHECK (tahun >= 2000 AND tahun <= 2025),
  warna character varying NOT NULL,
  kilometer numeric NOT NULL,
  plat_nomor character varying NOT NULL,
  tanggal_pajak date NOT NULL,
  harga_beli numeric NOT NULL,
  sumber_dana_1_id integer NOT NULL REFERENCES companies(id),
  nominal_dana_1 numeric NOT NULL,
  sumber_dana_2_id integer REFERENCES companies(id),
  nominal_dana_2 numeric DEFAULT 0,
  keterangan text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.pembelian ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "select_pembelian" ON public.pembelian
  FOR SELECT USING (true);

CREATE POLICY "insert_pembelian" ON public.pembelian
  FOR INSERT WITH CHECK (true);

CREATE POLICY "update_pembelian" ON public.pembelian
  FOR UPDATE USING (true);

CREATE POLICY "delete_pembelian" ON public.pembelian
  FOR DELETE USING (true);
